STORDIS/orca_ui

src/components/tabbedpane/interfaceDataTable.jsx, src/components/tabbedpane/tabbedPaneTable.scss
=> Apply Config button and text

package-lock.json, package.json, public/index.html, src/LogContext.js, src/components/logpane/logpane.jsx, src/components/logpane/logpane.scss, src/components/navbar/Discovery_btn.jsx, src/components/tabbedpane/TabbedPane.jsx, src/components/tabbedpane/interfaceDataTable.jsx, src/components/tabbedpane/portChDataTable.jsx, src/components/tabbedpane/portGroupTable.jsx, src/pages/home/Home.jsx
Fixes #33 
added the different column to log panel.
added color coding.
added time stamp.
Further need to integrate with the backend apis.
=> Log panel on UI   #33

src/components/logpane/logpane.jsx, src/components/tabbedpane/datatablesourse.js
Fixes #66
added regex to data column which will check for Management text and make it un editable.  
Added indentation to make it better readable.
=> added condition which doesnt allow to edit if Management

src/components/tabbedpane/MembersSelection.js, src/components/tabbedpane/portChDataTable.jsx
I have added the Modal in Member Field as we have in Vlan
=> Port channel member interface

src/App.scss, src/backend_rest_urls.js, src/components/PortChannelForm.jsx, src/components/VlanForm.jsx, src/components/logpane/logpane.jsx, src/components/logpane/logpane.scss, src/components/navbar/DiscoveryForm.jsx, src/components/navbar/Discovery_btn.jsx, src/components/tabbedpane/Form.scss, src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/interfaceDataTable.jsx, src/components/tabbedpane/portChDataTable.jsx, src/components/tabbedpane/portGroupTable.jsx, src/components/tabbedpane/tabbedPaneTable.scss, src/components/tabbedpane/vlanTable.jsx
=> #77 vlan issues

src/App.scss, src/components/PortChannelForm.jsx, src/components/navbar/DiscoveryForm.jsx, src/components/tabbedpane/MembersSelection.js, src/components/tabbedpane/interfaceDataTable.jsx, src/components/tabbedpane/portChDataTable.jsx, src/components/tabbedpane/portGroupTable.jsx, src/components/tabbedpane/tabbedPaneTable.scss, src/components/tabbedpane/vlanTable.jsx, src/utils/auth.js
Fixes #78 
Fixed all the 5-sub issue listed.
=> #78 port channel config issues

src/App.scss, src/backend_rest_urls.js, src/components/PortChannelForm.jsx, src/components/logpane/logpane.jsx, src/components/navbar/Discovery_btn.jsx, src/pages/layout/Layout.jsx, src/pages/layout/Layout.scss
new feature #33 
Added clear button for deletion of log in UI and also in backend.
Fixed the issue of not loading discovered devices after discovery and also added discovery logs.
=> Clear btn and some fix

src/components/PortChannelForm.jsx, src/components/VlanForm.jsx, src/components/logpane/logpane.jsx, src/components/tabbedpane/MembersSelection.js, src/components/tabbedpane/TabbedPane.jsx, src/components/tabbedpane/interfaceDataTable.jsx, src/components/tabbedpane/portChDataTable.jsx, src/components/tabbedpane/portGroupTable.jsx, src/components/tabbedpane/vlanTable.jsx, src/pages/layout/Layout.jsx, src/utils/dissableConfigContext.js, src/utils/logpannelContext.js
fixes #63 
added disabled apply config Boolean variable globally which will be get true once Api call is done (put or delete) and will make the apply config button disabled overall unless the Api responds back with success or failure.
=> apply config global btn added

package-lock.json, package.json, src/backend_rest_urls.js, src/components/PortChannelForm.jsx, src/components/logpane/logpane.jsx, src/components/navbar/Discovery_btn.jsx, src/components/sidebar/Sidebar.jsx, src/components/tabbedpane/Deviceinfo.jsx, src/components/tabbedpane/TabbedPane.jsx, src/components/tabbedpane/bgpTable.jsx, src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/mclagDataTable.jsx, src/components/tabbedpane/portChDataTable.jsx, src/pages/Login/login.jsx, src/pages/error/errorPage.jsx, src/pages/layout/Layout.jsx, src/pages/orcask/orcAsk.jsx, src/pages/orcask/orcAsk.scss
fixes [#5](https://github.com/STORDIS/ORCASK/issues/5)
Added charts and table to make the Json visually enhanced.
=> Orcask enhancement

src/pages/orcask/orcAsk.scss
=> some css fix

src/pages/orcask/orcAsk.jsx
fixes [#92](https://github.com/STORDIS/orca_ui/issues/92)
Added enter to call api and shift enter to go to next line
=> added enter to submit

src/pages/orcask/orcAsk.jsx, src/pages/orcask/orcAsk.scss
fixes #94 
fixed the scrolling issue and some CSS fixes.
=> fixed scrolling issue

src/pages/graphsNcharts/googleChart/googleChart.jsx, src/pages/graphsNcharts/sigmaGraph/sigmaGraph.jsx, src/pages/orcask/orcAsk.jsx
fixed the format change from backend
=> Orcask fix

src/components/logpane/logpane.jsx
fixes #114 
updated the log panel with respective to backend changes.
=> log pannel fix

package-lock.json, package.json, src/pages/orcask/components/historyChatSection.jsx, src/pages/orcask/orcAsk.jsx
fixes #113 
Fixed the multiple prompt issue which was occurring when prompt was copied from bookmark and request was sent resulted in creating multiple duplicate messages in UI
added tooltips for buttons with only icons
=> copying bookmark resending request issue

src/components/tabbedpane/Datatable.jsx, src/components/tabbedpane/datatablesourse.js, src/utils/backend_rest_urls.js
fixes [#41](https://github.com/STORDIS/orca_nw_lib/issues/41)
add the additional interface params to show in UI 
- alias 
- lanes 
- adv_speeds
- link_training
- autoneg
speed drop down in interface UI is showing speeds from valid_speeds array only and the current selected speed will be show at first
=> Interface new params

src/components/tabbedpane/Datatable.jsx, src/utils/backend_rest_urls.js
Modified the remove device button in sync with new api
=> modified the delete function api

src/components/tabbedpane/datatablesourse.js
fixes [#56](https://github.com/STORDIS/orca_nw_lib/issues/56) orca_ui
added functionality where autoneg is editable. 
Drop down added with off and on option which can be selected.
=> added functionality to edit autoneg

src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/interfaces/interfaceDataTable.jsx
fixes [#62](https://github.com/STORDIS/orca_nw_lib/issues/62)
added functionality to configure the adv speed and link training
dropdown added for both with relevant options
=> added editable feild for adv_speed and link training

src/components/tabbedpane/Form.scss, src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/vlan/VlanForm.jsx, src/components/tabbedpane/vlan/vlanMemberForm.jsx, src/components/tabbedpane/vlan/vlanTable.jsx, src/utils/backend_rest_urls.js
fixes #104 
In vlan member selection by default the selected item will be empty.
Autostate of vlan is a dropdown with "enable" and "disable" options.
In vlan when Ip is selected autostate must will disabled and vice versa.
in vlan status is renamed to admin status.
=> Vlan aditional fix

src/App.scss, src/components/logpane/logpane.jsx, src/components/logpane/logpane.scss, src/components/navbar/navbar.scss, src/components/sidebar/Sidebar.jsx, src/components/sidebar/sidebar.scss, src/components/tabbedpane/Datatable.jsx, src/components/tabbedpane/TabbedPane.jsx, src/components/tabbedpane/bgp/bgpTable.jsx, src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/interfaces/interfaceDataTable.jsx, src/components/tabbedpane/mclag/mclagDataTable.jsx, src/components/tabbedpane/portchannel/portChDataTable.jsx, src/components/tabbedpane/portgroup/portGroupTable.jsx, src/components/tabbedpane/tabbedPaneTable.scss, src/components/tabbedpane/vlan/vlanTable.jsx, src/pages/home/Home.jsx, src/pages/layout/Layout.jsx, src/pages/layout/Layout.scss
fixes #127 
fixed the bellow issues 
portgroup tab shoots the above pasted error
portgroup fields except speed must not be editable
reset back the zoom to normal i.e., 100%
disabling of the table is not working properly as it reloads the table
remove the config success and failed message
remove the popup messages
port group sorting is not working for column "ID"
=> Resizable and other fixes

src/components/tabbedpane/interfaces/interfaceDataTable.jsx, src/components/tabbedpane/portchannel/portChDataTable.jsx, src/components/tabbedpane/vlan/vlanMemberForm.jsx, src/components/tabbedpane/vlan/vlanTable.jsx
fixes 
- multiple changes in interface tab
- multiple changes in vlan tab
- member addition and deletion in vlan
=> vlan and interfaces fix

src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/interfaces/interfaceDataTable.jsx, src/components/tabbedpane/mclag/mclagDataTable.jsx, src/components/tabbedpane/mclag/mclagForm.jsx, src/components/tabbedpane/mclag/mclagMemberForm.jsx, src/components/tabbedpane/portchannel/portChDataTable.jsx
fixes #139 
- added dropdown in mclag addition form for peerlink which contains ethernet and portchannels
- added same drop down in table when peerlink cell is clicked for editing
=> added ethernet and portchannels as dropdown

src/components/tabbedpane/portchannel/PortChVlanForm.jsx, src/components/tabbedpane/vlan/VlanForm.jsx, src/components/tabbedpane/vlan/vlanMemberForm.jsx, src/components/tabbedpane/vlan/vlanTable.jsx, src/utils/backend_rest_urls.js
fixes #137 
Enabled the remove button for a specific vlan member 
- tested single deletion of trunk vlan 
- tested single deletion of acess vlan 
- tested deletion of all vlan (remove all)
=> enabled delete button and added single vlan remove button

src/components/navbar/DiscoveryForm.jsx, src/components/tabbedpane/Datatable.jsx, src/components/tabbedpane/Form.scss, src/components/tabbedpane/mclag/mclagDataTable.jsx, src/components/tabbedpane/portchannel/PortChVlanForm.jsx, src/components/tabbedpane/vlan/VlanForm.jsx, src/components/tabbedpane/vlan/vlanMemberForm.jsx, src/components/tabbedpane/vlan/vlanSagIpForm.jsx, src/components/tabbedpane/vlan/vlanTable.jsx, src/utils/backend_rest_urls.js
fixes [#40](https://github.com/STORDIS/orca_backend/issues/40)
- deletion of ip and sag ip i.e, once sag ip or ip is added then we can remove it and send null which will call delete api 
- removing description or adding empty string for description
- deletion and configuration / update will work simultaneously
this PR is dependent on  
- Library - [Issue in deletion of vlan properties - lib - #40 STORDIS/orca_nw_lib#79](https://github.com/STORDIS/orca_nw_lib/pull/79)
- backend - [Issue in deletion of vlan properties -b- #40 #50](https://github.com/STORDIS/orca_backend/pull/50)
=> Issue in deletion of vlan properties - ui - #40

src/components/logpane/logpane.jsx, src/components/navbar/DiscoveryForm.jsx, src/components/navbar/Navbar.jsx, src/components/tabbedpane/EditableHeaderComponent.js, src/components/tabbedpane/bgp/bgpTable.jsx, src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/mclag/mclagDataTable.jsx, src/components/tabbedpane/portchannel/PortChVlanForm.jsx, src/components/tabbedpane/portchannel/PortChannelForm.jsx, src/components/tabbedpane/portchannel/portChDataTable.jsx, src/components/tabbedpane/portchannel/portChMemberForm.jsx, src/components/tabbedpane/stp/stpDataTable.jsx, src/components/tabbedpane/vlan/VlanForm.jsx, src/components/tabbedpane/vlan/vlanSagIpForm.jsx, src/components/tabbedpane/vlan/vlanTable.jsx, src/pages/orcask/components/historyChatSection.jsx, src/pages/orcask/orcAsk.jsx, src/utils/backend_rest_urls.js, src/utils/common.js
fixes #151 
added interface mode for vlan in portchannel
added checks for vlan only TRUNK vlans can have multiple vlans and ACCESS can have only one vlan
=> Separate column #151

src/components/logpane/logpane.jsx, src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/portchannel/PortChVlanForm.jsx, src/components/tabbedpane/portchannel/PortChannelForm.jsx, src/components/tabbedpane/portchannel/portChDataTable.jsx, src/components/tabbedpane/portchannel/portChMemberForm.jsx, src/pages/orcask/components/historyChatSection.jsx, src/pages/orcask/orcAsk.jsx
fixes for issue https://github.com/STORDIS/orca_ui_test/issues/5#issuecomment-2331800870
issue of deleting portchannel member 
issue for changing fallback and other boolean config fixes
issue in orcask fixed which was giving error when response was in object formate
=> Test case support

src/App.scss, src/components/tabbedpane/Form.scss, src/components/tabbedpane/TabbedPane.jsx, src/components/tabbedpane/datatablesourse.js, src/components/tabbedpane/interfaces/interfaceDataTable.jsx, src/components/tabbedpane/interfaces/primarySecondaryForm.jsx, src/utils/backend_rest_urls.js
fixes #165 
- added functionality to add primary and multiple secondary ips
- remove for particular ip added 
- remove all button added
=> Interface primary secondary ip configuration

src/components/tabbedpane/datatablesourse.js, src/pages/orcask/components/chatsection.jsx, src/pages/orcask/components/dynamicRender.jsx, src/pages/orcask/components/historyChatSection.jsx, src/pages/orcask/orcAsk.scss, src/utils/backend_rest_urls.js
fixes #171 
Temporary fix 
this includes the adaption of new Json or response format of the history API. But as discussed this will be changed in future and will be rectified accordingly
=> Orcask message format fix

src/utils/backend_rest_urls.js
=> Orca Sonic Release Upgrade

src/components/tabbedpane/interfaces/interfaceDataTable.jsx, src/pages/ZTPnDHCP/CredentialsForm.jsx, src/pages/home/Home.jsx
fixes #181 
- color based connection response
- IP validation
- Provision to remove the DHCP server configuration.
- Discover DHCP button renamed.
=> Dhcp issues

src/components/logpane/logpane.jsx, src/components/logpane/logpane.scss, src/components/modal/dhcpScanLogModal.jsx, src/components/tabbedpane/datatablesourse.js, src/pages/home/Home.jsx, src/pages/layout/Layout.jsx, src/utils/backend_rest_urls.js
fixes #186 
- added new api for scanning dhcp devices
- dhcp table in home will show the latest dhcp scanned task result
=> Dhcp scanning

src/App.scss, src/components/logpane/logpane.jsx, src/components/logpane/logpane.scss, src/components/modal/dhcpScanLogModal.jsx, src/components/modal/discoveryLogModal.jsx, src/components/modal/setupLogModal.jsx, src/components/navbar/DiscoveryForm.jsx, src/components/navbar/Navbar.jsx, src/components/navbar/navbar.scss, src/components/tabbedpane/bgp/bgpForm.jsx, src/components/tabbedpane/mclag/mclagForm.jsx, src/pages/ZTPnDHCP/CredentialsForm.jsx, src/pages/home/Home.jsx, src/pages/home/home.scss, src/pages/layout/Layout.scss, src/pages/setup/setup.jsx, src/utils/pointerStore.js
fixes #189 
- added all 5 pointers in top nav bar
- some optimization
=> UI pointers
